# Generated by Django 4.0.4 on 2022-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_delete_user'),
    ]

    operations = [
    ]
